fix/tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,11 +42,10 @@ jobs:
         run: |
           gunzip -c service-test.tar.gz | docker load
       - name: Prepare report dir on host
-        run: mkdir -p reports/ci && chmod -R 777 reports/ci
+        run: mkdir -p ${{ github.workspace }}/reports/ci && chmod -R 777 ${{ github.workspace }}/reports/ci
       - name: Show workspace
         run: |
           echo "PWD=$(pwd)"
-          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
           ls -lah
       - name: Run service tests
         run: |
@@ -54,14 +53,14 @@ jobs:
       - name: Debug list
         if: always()
         run: |
-          echo "Looking for reports/ci/coverage.xml in $(pwd)"
-          ls -lah reports || true
-          ls -lah reports/ci || true
-          test -f reports/ci/coverage.xml && echo "FOUND coverage.xml" || echo "NOT FOUND"
+          echo "Looking for ${{ github.workspace }}/reports/ci/coverage.xml in $(pwd)"
+          ls -lah ${{ github.workspace }}/reports || true
+          ls -lah ${{ github.workspace }}/reports/ci || true
+          test -f ${{ github.workspace }}/reports/ci/coverage.xml && echo "FOUND coverage.xml" || echo "NOT FOUND"
       - name: Upload coverage xml
         uses: actions/upload-artifact@v4
         with:
           name: coverage-xml
-          path: reports/ci/coverage.xml
+          path: ${{ github.workspace }}/reports/ci/coverage.xml
           if-no-files-found: error
 
